name: build-n-push
on:
  workflow_dispatch: # allows manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-n-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Config cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: |
          nix build .#image
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          docker image load < result
          docker image tag telegram-spongifybot ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker image tag telegram-spongifybot ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker image push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
