name: nix-flake-update
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 2 * * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        run: |
          nix flake update
      - name: Push
        continue-on-error: true
        env:
          HASH: ${{ hashFiles('flake.lock') }}
        run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config --global push.autoSetupRemote true
          git add flake.lock
          git commit --allow-empty-message -m ""
          git switch --orphan actions/nix-flake-update/${HASH::14}
          git checkout ${{ github.ref_name }} -- flake.lock
          git commit -m "nix flake update"
          git push
